(define-module (src quiz-loader)
  #:use-module (json)
  #:export (QNR-ERROR-FILE-NOT-FOUND
            QNR-ERROR-JSON-PARSING
            QNR-ERROR-PARSED-NO-TOP-LEVEL-FIELD
            QNR-ERROR-PARSED-EMPTY-QUESTIONS
            QNR-ERROR-PARSED-QUESTION-NOT-JSON-OBJECT
            QNR-ERROR-PARSED-MISSING-FIELD
            QNR-ERROR-PARSED-WRONG-TYPE-QUERY
            QNR-ERROR-PARSED-WRONG-TYPE-CHOICES
            QNR-ERROR-PARSED-WRONG-TYPE-EXPECTED-RESPONSE-COUNT
            qnr-load-quiz-file
            ;; Accessors
            qnr-dto-question-query
            qnr-dto-question-choices
            qnr-dto-question-expected-response-count))

;; Built-in Errors
(define BUILT-IN-ERROR-SYSTEM-ERROR 'system-error)
;; Dependency Errors
(define MODULE-ERROR-INVALID-JSON 'json-invalid) ;; Exception from guile-json.

;; Parsing errors
(define QNR-NO-LOADING-ERROR 'qnr-no-loading-error)
(define QNR-ERROR-FILE-NOT-FOUND 'qnr-error-file-not-found)
(define QNR-ERROR-JSON-PARSING 'qnr-error-invalid-json)
(define QNR-ERROR-PARSED-NO-TOP-LEVEL-FIELD
  'qnr-error-no-top-level-record-field)
(define QNR-ERROR-PARSED-EMPTY-QUESTIONS
  'qnr-error-no-questions-in-json)
(define QNR-ERROR-PARSED-QUESTION-NOT-JSON-OBJECT
  'qnr-error-parsed-quiz-dto-wrong-type-not-a-json-object)
(define QNR-ERROR-PARSED-MISSING-FIELD
  'qnr-error-parsed-missing-field)
(define QNR-ERROR-PARSED-WRONG-TYPE-QUERY
  'qnr-error-parsed-wrong-type-query)
(define QNR-ERROR-PARSED-WRONG-TYPE-CHOICES
  'qnr-error-parsed-wrong-type-choices)
(define QNR-ERROR-PARSED-WRONG-TYPE-EXPECTED-RESPONSE-COUNT
  'qnr-error-parsed-wrong-type-expected-response-count)


;; Other constants
(define TOP-LEVEL-KEY-NAME "questions")
(define TOP-LEVEL-KEY-NAME-AS-SYMBOL 'questions)

;;  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(define (qnr-load-quiz-file path)
  "Read the file given by PATH and return a list of `qnr-dto-question` inside a
field inside an `qnr-quetsion-dto-list` record."
  ;; Nested Helpers ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (define (create-records-from-parsed-json)
    (let ((questions (access-list-from-dto-question-record-list
                      (form-parsed-json-into-dto-questions-list
                       (get-parsed-json-from-file path)))))
      (validate-questions questions)
      questions))
  (define (handle-failure-to-parse-json key . args)
    (throw QNR-ERROR-JSON-PARSING))
  ;;  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (catch MODULE-ERROR-INVALID-JSON
    create-records-from-parsed-json
    handle-failure-to-parse-json))

(define (form-parsed-json-into-dto-questions-list parsed-json)
  (with-exception-handler
      (lambda (exc)
        (throw QNR-ERROR-PARSED-QUESTION-NOT-JSON-OBJECT)
        #f)
    (lambda () (scm->qnr-dto-question-list parsed-json))))

(define (get-parsed-json-from-file path)
  ;; Nested Helpers ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (define (read-quiz-json-file)
    (call-with-input-file path (lambda (port) (parse-quiz-json-file port))))
  (define (handle-failure-to-open-file key . args)
    (throw QNR-ERROR-FILE-NOT-FOUND))
  ;;  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (catch BUILT-IN-ERROR-SYSTEM-ERROR
    read-quiz-json-file
    handle-failure-to-open-file))

(define (parse-quiz-json-file port)
  (json->scm port #:ordered #t))

;; JSON Records ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(define-json-type <qnr-dto-question>
  (query)
  (choices)
  (expected-response-count))

(define-json-type <qnr-dto-question-list>
  ;; WARNING: hardcoded `questions` due to macro
  (questions TOP-LEVEL-KEY-NAME #(<qnr-dto-question>)))

;; WORKAROUND: Redefine the accessor `qnr-dto-question-list-questions`
;; generated by `define-json-type` because that one breaks when called from
;; this file for some reason. Maybe related to
;; https://lists.gnu.org/archive/html/guile-user/2023-08/msg00010.html.
;; Redefine under a different name as not to shadow the previous definition.
(define (access-list-from-dto-question-record-list record)
  ((record-accessor <qnr-dto-question-list> TOP-LEVEL-KEY-NAME-AS-SYMBOL) record))

;; Validation ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(define ACCESSORS (list qnr-dto-question-query
                        qnr-dto-question-choices
                        qnr-dto-question-expected-response-count))

(define (validate-questions questions)
  "Validate that records in QUESTIONS are valid.

Checks to see if the parsed JSON properly conforms to the type
`<qnr-dto-question>`."
  (when (unspecified? questions)
    (throw QNR-ERROR-PARSED-NO-TOP-LEVEL-FIELD))

  (when (null? questions)
    (throw QNR-ERROR-PARSED-EMPTY-QUESTIONS))

  (let ((question (car questions)))
    (validate-field-presence question)
    ;; Check query before any other field so other validators can reference the
    ;; query to help identify the location of the error in the JSON file. That
    ;; is the query can be passed as an argument to `throw`. Choose query for
    ;; this purpose instead of another field because it is more likely to be
    ;; unique.
    (validate-query question)
    (validate-choices question)
    (validate-expected-response-count question)))

(define (validate-field-presence question)
  (for-each
   (lambda (accessor)
     (when (unspecified? (accessor question))
       (throw 'qnr-error-parsed-missing-field accessor)))
   ACCESSORS))

(define (validate-query question)
  (let ((query (qnr-dto-question-query question)))
    (unless (string? query)
      (throw QNR-ERROR-PARSED-WRONG-TYPE-QUERY))))

(define (validate-choices question)
  "Assumes field query is already valid."
  (unless (vector? (qnr-dto-question-choices question))
    (throw-with-query QNR-ERROR-PARSED-WRONG-TYPE-CHOICES question)))

(define (validate-expected-response-count question)
  "Assumes field query is already valid."
  (unless (integer? (qnr-dto-question-expected-response-count question))
    (throw-with-query QNR-ERROR-PARSED-WRONG-TYPE-EXPECTED-RESPONSE-COUNT question)))

(define (throw-with-query key question)
  (let ((query (qnr-dto-question-query question)))
    (throw key query)))
